### ISSUE TITLE
MetalLB not getting IP range

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener-extension-provider-equinix-metal#175]
**How to categorize this issue?**

/area networking
/kind bug
/priority 1

**What happened**:
Bringing up a new shoot on EM fails due to MetalLB not getting an IP Range assigned.
The issue is that the EQXM gardener extension provider is using a version of CCM that requires a different env var.
So the CCM doesn’t know to manage metallb, so it doesn’t, so metallb doesn’t get the config it needs, so there is no load balancer, so the vpn cannot connect
**What you expected to happen**:
Shoot coming up
**How to reproduce it (as minimally and precisely as possible)**:
Try to deploy a shoot on EM
**Anything else we need to know?**:
This fix should be related and just needs to be released: https://github.com/gardener/gardener-extension-provider-equinix-metal/commit/f9e53db4b912beda3849aa6c80f1215d52ff0347#diff-75802b9521073ccc96b6346240019f45d11d461d1a8e7e207ad63aab13fcb01c
**Environment**:

- Gardener version (if relevant):
- Extension version: 2.0.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by christianhuening** [comment]
cc @deitch

**Comment by deitch** [comment]
Thanks for opening the issue @christianhuening .

The fix linked to above fixes this; we just haven't cut a release since before then. The last release v2.0.0 was on 27 Aug, we have merged in around 7 PRs since then. Given the minimal changes - that bug fix, updated vending, support for k8s 1.22 - I think it qualifies for a minor release, so 2.1.0.

@rfranzke I don't actually recall how we cut releases here. Can you direct me through it?

**Comment by rfranzke** [comment]
A release can be built by triggering the `master-release-job` here: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-provider-equinix-metal-master

Do you have permissions for it?

**Comment by deitch** [comment]
It doesn't look like it. I can see things, and login, but cannot make changes like kicking off a job (I think). I wouldn't know how to set the release version anyways.

**Comment by rfranzke** [comment]
The release version is defined here: https://github.com/gardener/gardener-extension-provider-equinix-metal/blob/8c88e933ce8e991431ce6764fafca28326b03b0d/VERSION#L1, so the next version would be `v2.1.0`

You typically don't need to do anything here, it will be auto-bumped with every release (i.e., when we click the button it will become `v2.2.0-dev`).

For now, do you want me to click the button to get the release?
For the access question I suggest to reach out to @ccwienk or @AndreasBurger or @jkrayl (Concourse maintainers).

**Comment by deitch** [comment]
> For now, do you want me to click the button to get the release?

Would you please?

**Comment by rfranzke** [comment]
Here it is: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-provider-equinix-metal-master/jobs/master-release-job/builds/1

**Comment by deitch** [comment]
Thanks. When it is done, it will cut the release on GitHub as well as push out images, etc.? Take care of everything?

**Comment by rfranzke** [comment]
Yes

**Comment by schrodit** [comment]
should be already resolved. Feel free to re-open if this issue persists.
