### ISSUE TITLE
Access to CI Pipelines

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener-extension-provider-equinix-metal#301]
Dear Gardener CI/CD Team,

I'm on of the maintainers for the equinix extension and would like to request access for those pipelines to be able to trigger releases and hotfixes.

Kind regards,
Tim

**Comment by zkdev** [comment]
Hi @schrodit,

I granted you access to the [corresponding pipelines](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/gardener-extension-provider-equinix-metal-master).

Could you please confirm that you have access and everything is working as expected?

**Comment by zkdev** [comment]
Pipelines are green, I am closing here.
Please get in touch in case of questions :-) .
