### ISSUE TITLE
Access to CI/CD and org/repo membership

### ISSUE THREAD

**Issue by RiRa12621** [gardener/gardener-extension-provider-equinix-metal#323]
Dear Gardener Team,

as we would like to increase the (human) resources invested into maintaining this extension, I kindly request to be added as maintainer as well as getting access to the trigger the pipelines.

Best Regards

Rick 

cc @schrodit

**Comment by NiclasMoldenhauer** [comment]
Approved from management side 👍
Please proceed @8R0WNI3

**Comment by 8R0WNI3** [comment]
Hi @RiRa12621 ,

I granted you access to this repository and the [corresponding pipelines](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/gardener-extension-provider-equinix-metal-master).

Could you please confirm that you have access and everything is working as expected, e.g. by triggering a head-update job?

**Comment by RiRa12621** [comment]
works great, thanks. Closing as complete.
